DATABASE_URL = postgres://VALUE1:VALUE2@VALUE3.eu-west-1.compute.amazonaws.com:5432/VALUE4 # decrypted on the repo


SQLALCHEMY_TRACK_MODIFICATIONS = False

ALGORITHMS
API_AUDIENCE
AUTH0_DOMAIN
DATABASE_URL
TEST_AUTH
KEY