"""empty message

Revision ID: 84bd3966fbfa
Revises: 
Create Date: 2021-03-20 00:07:27.488996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84bd3966fbfa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Questions', sa.Column('sentence', sa.String(), nullable=True))
    op.drop_column('Questions', 'fullSentence')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Questions', sa.Column('fullSentence', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Questions', 'sentence')
    # ### end Alembic commands ###
